oss:
  region: "cn-chengdu"          # 存储空间区域
  bucket: "detection-pcb-test"      # Bucket 名称
  endpoint: ""                      # 可选自定义 Endpoint
  key_prefix: "python_upload/"            # 对象名称前缀（可选）ion: